/**
 * DefendAble — Legal document templates (Engine → Manage)
 * Generates the three core response documents from a case handoff pack:
 *   holdingResponse  (docKey 'loa')              — acknowledge + investigate
 *   defenceLetter    (docKey 'lor')              — extraordinary circumstances defence
 *   settlementOffer  (docKey 'settlement_offer') — without-prejudice resolution
 * Every document files as status 'draft' — nothing leaves without G2 lawyer
 * approval in Manage. The system creates the layout; the lawyer makes the judgment.
 */
var DefendAbleDocTemplates = (function () {
  'use strict';

  var DRAFT_BANNER =
    '================ DRAFT — AWAITING LAWYER APPROVAL (G2) ================\n' +
    'Generated by DefendAble from the confirmed factual record and signed-off\n' +
    'legal position. Review, complete bracketed fields, and approve before send.\n' +
    '=======================================================================\n\n';

  /* ── jurisdiction-aware statutory language ── */
  function statute(jurisdiction) {
    var uk = String(jurisdiction || '').toUpperCase().indexOf('UK') === 0;
    return {
      isUK: uk,
      regName: uk
        ? 'Regulation (EC) No 261/2004 as retained in UK law ("UK261")'
        : 'Regulation (EC) No 261/2004 ("EC261")',
      regShort: uk ? 'UK261' : 'EC261',
      art53: uk ? 'Article 5(3) UK261' : 'Article 5(3) EC261',
      art7: uk ? 'Article 7 UK261' : 'Article 7 EC261',
      art9: uk ? 'Article 9 UK261' : 'Article 9 EC261',
      currency: uk ? '£' : '€',
      protocol: uk
        ? 'This letter is sent in accordance with the Practice Direction on Pre-Action Conduct and Protocols.'
        : 'This letter is sent in accordance with applicable pre-action requirements in the relevant jurisdiction.'
    };
  }

  /* ── classification-specific defence basis ── */
  var DEFENCE_BASIS = {
    weather: 'The disruption was caused by adverse meteorological conditions incompatible with the safe operation of the flight. Such conditions are expressly contemplated by Recital 14 of the Regulation and are, by their nature and origin, not inherent in the normal exercise of an air carrier’s activity and beyond its actual control.',
    atfm: 'The disruption resulted from an air traffic management decision imposing flow restrictions on the flight concerned. Recital 15 of the Regulation expressly contemplates such circumstances, and the Court of Justice confirmed in Moens (C-159/18) that events of this character are outside the operating carrier’s control.',
    atc: 'The disruption resulted from an air traffic control restriction beyond the operating carrier’s control, as expressly contemplated by Recital 15 of the Regulation.',
    'third-party-ia': 'The disruption was caused by industrial action affecting a third-party service provider whose workforce the operating carrier neither employs nor controls. Such action is not inherent in the carrier’s activity and is beyond its actual control.',
    birdstrike: 'The disruption followed a collision between the aircraft and wildlife, requiring mandatory safety inspection. The Court of Justice held in Pešková (C-315/15) that a bird strike is an extraordinary circumstance, being neither inherent in the carrier’s normal activity nor within its control.',
    medical: 'The disruption resulted from an onboard medical emergency requiring diversion in accordance with the commander’s overriding duty to protect life. This is an unforeseeable third-party event outside the carrier’s control.',
    security: 'The disruption arose from a security event requiring action mandated by the competent authorities, expressly contemplated by Recital 14 of the Regulation and beyond the operating carrier’s control.',
    'disruptive-pax': 'The disruption was caused by the unruly conduct of a passenger, requiring intervention in the interests of flight safety. The Court of Justice held in LE v TAP (C-74/19) that such conduct constitutes an extraordinary circumstance.',
    'airport-closure': 'The disruption resulted from the closure or restriction of airport infrastructure by its operator, a matter outside the operating carrier’s control (Moens, C-159/18).',
    'ground-damage': 'The disruption resulted from damage caused by a third party outside the operating carrier’s control.',
    'natural-disaster': 'The disruption resulted from a natural event incompatible with the safe operation of the flight, expressly contemplated by Recital 14 of the Regulation.',
    'crew-fdp': 'The crew duty limitation engaged on the flight arose as the direct consequence of an upstream extraordinary circumstance, and the causal chain from that event to the disruption remained unbroken.'
  };

  function esc(s) { return String(s == null ? '' : s); }

  function normaliseAuthorities(auths) {
    var binding = [], persuasive = [];
    if (!auths) return { binding: binding, persuasive: persuasive };
    if (Array.isArray(auths)) {
      auths.forEach(function (a) {
        var name = a.citation || a.ref || a.name || String(a);
        var w = String(a.weight || '').toLowerCase();
        (w === 'binding' ? binding : persuasive).push(name);
      });
    } else {
      (auths.binding || []).forEach(function (a) { binding.push(a.citation || a.ref || a.name || String(a)); });
      (auths.persuasive || []).forEach(function (a) { persuasive.push(a.citation || a.ref || a.name || String(a)); });
    }
    return { binding: binding, persuasive: persuasive };
  }

  function factsRecital(pack) {
    var f = pack.factsSection || {};
    var lines = [];
    var head = [f.flightNum, f.route, f.flightDate].filter(Boolean).join(' · ');
    if (head) lines.push(head + (f.delay ? ' · recorded delay ' + f.delay : ''));
    (f.causalLabels || []).forEach(function (c) { lines.push(c); });
    return lines;
  }

  function today() {
    return new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  }

  function sigBlock(pack) {
    return 'Yours faithfully,\n\n[NAME]\n[POSITION]\nFor and on behalf of [AIRLINE]\nRef: ' + esc((pack.meta || {}).caseRef || '[CASE REF]');
  }

  function reLine(pack) {
    var f = pack.factsSection || {};
    return 'Re: ' + esc((pack.meta || {}).claimant || '[CLAIMANT NAME]') +
      ' — Flight ' + esc(f.flightNum || '[FLIGHT]') +
      (f.route ? ' (' + f.route + ')' : '') +
      (f.flightDate ? ', ' + f.flightDate : '');
  }

  /* ────────────────────────────────────────────────
     1 · HOLDING RESPONSE  (Letter of Acknowledgement)
  ──────────────────────────────────────────────── */
  function holdingResponse(pack) {
    var S = statute((pack.factsSection || {}).jurisdiction);
    var body =
      DRAFT_BANNER +
      today() + '\n\n' +
      esc((pack.meta || {}).solicitor || '[CLAIMANT SOLICITOR]') + '\n\n' +
      'Dear Sirs,\n\n' +
      reLine(pack) + '\n\n' +
      'We write on behalf of [AIRLINE] to acknowledge receipt of your letter of claim dated [LOC DATE] in respect of the above flight.\n\n' +
      'The circumstances of the disruption are under active investigation. The operational records for the flight concerned — including the line of flying of the operating aircraft, meteorological and air traffic management records, and the carrier’s contemporaneous operational logs — are being retrieved and reviewed.\n\n' +
      'We will provide a substantive response within 30 days of the date of this letter. ' + S.protocol + '\n\n' +
      'In the meantime, no admission is made as to liability, and all of [AIRLINE]’s rights are expressly reserved, including in respect of the defence of extraordinary circumstances under ' + S.art53 + '.\n\n' +
      sigBlock(pack);
    return {
      docKey: 'loa',
      folderId: 'correspondence',
      name: 'Letter of Acknowledgement (draft)',
      filename: esc((pack.meta || {}).caseRef || 'case') + '-LOA-draft.txt',
      content: body
    };
  }

  /* ────────────────────────────────────────────────
     2 · DEFENCE LETTER  (Letter of Response)
  ──────────────────────────────────────────────── */
  function defenceLetter(pack) {
    var S = statute((pack.factsSection || {}).jurisdiction);
    var d = pack.decideSection || {};
    var auth = normaliseAuthorities(d.authorities);
    var basis = DEFENCE_BASIS[(pack.meta || {}).disruptionType] ||
      'The disruption was caused by an event which, by its nature and origin, was not inherent in the normal exercise of the operating carrier’s activity and was beyond its actual control.';

    var facts = factsRecital(pack);
    var factsText = facts.length
      ? facts.map(function (l, i) { return '  ' + (i + 1) + '. ' + l; }).join('\n')
      : '  [SET OUT THE FACTUAL CHRONOLOGY]';

    var authText = '';
    if (auth.binding.length) authText += 'We rely in particular on ' + auth.binding.join('; ') + '.';
    if (auth.persuasive.length) authText += (authText ? ' ' : '') + 'Further support is found in ' + auth.persuasive.join('; ') + '.';
    if (!authText) authText = 'We rely on the settled case law of the Court of Justice on Article 5(3), including Wallentin-Hermann (C-549/07).';

    var body =
      DRAFT_BANNER +
      today() + '\n\n' +
      esc((pack.meta || {}).solicitor || '[CLAIMANT SOLICITOR]') + '\n\n' +
      'Dear Sirs,\n\n' +
      reLine(pack) + '\n\n' +
      '1. BACKGROUND\n\n' +
      'This letter responds substantively to your client’s claim under ' + S.regName + '. The relevant factual chronology, drawn from the carrier’s contemporaneous operational records, is as follows:\n\n' +
      factsText + '\n\n' +
      '2. THE LEGAL FRAMEWORK\n\n' +
      'Under ' + S.art53 + ', an operating air carrier is not obliged to pay compensation under ' + S.art7 + ' if it can prove that the cancellation or delay was caused by extraordinary circumstances which could not have been avoided even if all reasonable measures had been taken. The two-limb test in Wallentin-Hermann (C-549/07) requires that the event (i) is not, by its nature or origin, inherent in the normal exercise of the carrier’s activity, and (ii) is beyond its actual control.\n\n' +
      '3. EXTRAORDINARY CIRCUMSTANCES\n\n' +
      basis + '\n\n' + authText + '\n\n' +
      '4. ALL REASONABLE MEASURES\n\n' +
      'The carrier deployed all resources at its disposal to avoid or mitigate the disruption. [SUMMARISE: standby aircraft and crew position; re-routing search across own services and other carriers; network recovery constraints on the day.] The measures taken satisfied the standard in Eglītis (C-294/10) without requiring intolerable sacrifices in the light of the capacity of the undertaking.\n\n' +
      '5. CARE AND ASSISTANCE\n\n' +
      'Passengers were provided with care and assistance in accordance with ' + S.art9 + '. [SUMMARISE: refreshments, meals, accommodation, transport and communications provided.]\n\n' +
      '6. CONCLUSION\n\n' +
      'For the reasons set out above, compensation under ' + S.art7 + ' is not payable and the claim is respectfully declined. This letter is written without prejudice to all of the carrier’s rights and contentions.\n\n' +
      sigBlock(pack);

    return {
      docKey: 'lor',
      folderId: 'legal_drafts',
      name: 'Letter of Response — extraordinary circumstances defence (draft)',
      filename: esc((pack.meta || {}).caseRef || 'case') + '-LOR-draft.txt',
      content: body
    };
  }

  /* ────────────────────────────────────────────────
     3 · SETTLEMENT OFFER  (without prejudice)
  ──────────────────────────────────────────────── */
  function settlementOffer(pack) {
    var S = statute((pack.factsSection || {}).jurisdiction);
    var amount = (pack.meta || {}).value || '[AMOUNT]';
    var body =
      DRAFT_BANNER +
      'WITHOUT PREJUDICE SAVE AS TO COSTS\n\n' +
      today() + '\n\n' +
      esc((pack.meta || {}).solicitor || '[CLAIMANT SOLICITOR]') + '\n\n' +
      'Dear Sirs,\n\n' +
      reLine(pack) + '\n\n' +
      'We refer to your client’s claim under ' + S.regName + '.\n\n' +
      'Without any admission of liability, and purely to avoid the disproportionate cost of contested proceedings, [AIRLINE] offers the sum of ' + amount + ' in full and final settlement of all claims arising out of the flight referred to above, including any claim to compensation, expenses, interest and costs.\n\n' +
      'This offer is open for acceptance for 14 days from the date of this letter, after which it is withdrawn without further notice. Acceptance should be communicated in writing, following which payment will be made within 14 days.\n\n' +
      'If this offer is not accepted and your client fails to obtain a more advantageous outcome, we reserve the right to draw this letter to the attention of the court on the question of costs.\n\n' +
      sigBlock(pack);
    return {
      docKey: 'settlement_offer',
      folderId: 'legal_drafts',
      name: 'Settlement offer — without prejudice (draft)',
      filename: esc((pack.meta || {}).caseRef || 'case') + '-Settlement-draft.txt',
      content: body
    };
  }

  /* ────────────────────────────────────────────────
     Verdict-driven selection — which drafts belong on this case
  ──────────────────────────────────────────────── */
  function draftsForPack(pack) {
    var v = String(((pack.decideSection || {}).verdict || (pack.meta || {}).classification || '')).toUpperCase();
    var docs = [holdingResponse(pack)];
    if (v.indexOf('SETTLE') >= 0) {
      docs.push(settlementOffer(pack));
    } else if (v.indexOf('DEFEND') >= 0 || v.indexOf('CONDITION') >= 0 || v.indexOf('HOLD') >= 0) {
      docs.push(defenceLetter(pack));
    }
    // JUDGMENT REQUIRED / unknown → holding response only; lawyer decides direction
    return docs;
  }

  return {
    holdingResponse: holdingResponse,
    defenceLetter: defenceLetter,
    settlementOffer: settlementOffer,
    draftsForPack: draftsForPack,
    _statute: statute,
    _defenceBasis: DEFENCE_BASIS
  };
})();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = DefendAbleDocTemplates;
}
