// ALL DATA AND HELPERS — embedded in every page
const USERS={
  SB:{id:'SB',name:'S. Booth',full:'Sarah Booth',role:'Head of Legal Ops',initials:'SB',lang:'en'},
  JP:{id:'JP',name:'J. Patel',full:'James Patel',role:'Senior Solicitor',initials:'JP',lang:'en'},
  KR:{id:'KR',name:'K. Rahman',full:'Kiran Rahman',role:'Solicitor',initials:'KR',lang:'en'},
  MD:{id:'MD',name:'M. Dupont',full:'Marie Dupont',role:'Juriste senior',initials:'MD',lang:'fr'},
  PL:{id:'PL',name:'P. Laurent',full:'Pierre Laurent',role:'Juriste',initials:'PL',lang:'fr'},
  CG:{id:'CG',name:'C. García',full:'Carlos García',role:'Abogado senior',initials:'CG',lang:'es'},
  IM:{id:'IM',name:'I. Martín',full:'Isabel Martín',role:'Abogada',initials:'IM',lang:'es'},
  EH:{id:'EH',name:'E. Hughes',full:'Emma Hughes',role:'Evidence Handling Specialist',initials:'EH',lang:'en',team:'evidence'},
};
const JURISDICTIONS={
  'england-wales':{name:'England & Wales',flag:'🇬🇧',lang:'en',limitationYears:6,limitationNote:'6 years — Limitation Act 1980',court:'County Court',procedureNote:'CPR Pre-Action Protocol. 21-day acknowledgement.',responseWindow:21,mediation:'optional',mediationNote:'ADR available but not mandatory.',keyDates:[{label:'Acknowledge LOC',days:21,urgency:'critical',note:'CPR Pre-Action Protocol'},{label:'Letter of Response',days:91,urgency:'important',note:'3 months from acknowledgement'},{label:'Limitation review',days:120,urgency:'watch',note:'6-year limitation'}],documents:{acknowledgement:'Letter of Acknowledgement',response:'Letter of Response',defence:'Defence (CPR Part 16)',witness:'Witness Statement (CPR Part 32)'},important:null},
  'france':{name:'France',flag:'🇫🇷',lang:'fr',limitationYears:5,limitationNote:'5 ans — art. 2224 Code civil',court:'Tribunal Judiciaire',procedureNote:'Médiation préalable OBLIGATOIRE depuis le 6 février 2026. Sans médiation, demande irrecevable.',responseWindow:60,mediation:'mandatory',mediationBody:'Médiateur du Tourisme et du Voyage (MTV)',mediationNote:'Médiation obligatoire depuis le 6 février 2026.',keyDates:[{label:'Répondre à la réclamation',days:60,urgency:'critical',note:'60 jours — avant médiation MTV'},{label:'Médiation préalable (MTV)',days:90,urgency:'critical',note:'OBLIGATOIRE depuis le 6 février 2026'},{label:'Assignation si échec',days:150,urgency:'important',note:'Tribunal Judiciaire par assignation'},{label:'Surveillance prescription',days:180,urgency:'watch',note:'Prescription 5 ans'}],documents:{acknowledgement:'Accusé de réception',response:'Lettre de réponse',defence:'Conclusions en défense',witness:'Attestation de témoin'},important:'ATTENTION : Médiation préalable obligatoire depuis le 6 février 2026. Sans cette étape, la demande est irrecevable.'},
  'spain':{name:'España',flag:'🇪🇸',lang:'es',limitationYears:5,limitationNote:'5 años — art. 1964 Código Civil',court:'Juzgado de lo Mercantil',procedureNote:'Reclamaciones ante el Juzgado de lo Mercantil. AESA puede iniciar expediente sancionador paralelo.',responseWindow:30,mediation:'available',mediationNote:'Mediación disponible pero no obligatoria.',keyDates:[{label:'Responder a la reclamación',days:30,urgency:'critical',note:'30 días — reclamación AESA'},{label:'Contestación a la demanda',days:20,urgency:'critical',note:'20 días hábiles desde notificación judicial'},{label:'Vigilancia prescripción',days:90,urgency:'watch',note:'Prescripción 5 años'}],documents:{acknowledgement:'Acuse de recibo',response:'Escrito de respuesta',defence:'Contestación a la demanda',witness:'Declaración testifical'},important:'AESA puede iniciar expediente sancionador paralelo, independiente del litigio civil.'},
};
const I18N={
  en:{work:'Work',requests:'Requests',insights:'Insights',dashboard:'Dashboard',intake:'Intake',cases:'Cases',cpr:'CPR',evidence:'Evidence',drafting:'Drafting',mi:'MI',knowledge:'Knowledge',repository:'Repository',myCases:'My cases',intakeQueue:'Intake queue',cprWatch:'CPR watch',myPipeline:'My pipeline',legalNews:'Legal & regulatory',networkOps:'Network & operations',liveSources:'Live sources',goodMorning:'Good morning',goodAfternoon:'Good afternoon',goodEvening:'Good evening',noUrgentDeadlines:'No urgent CPR deadlines this week',evidenceProgress:'Evidence progress',cprDeadlines:'CPR deadlines',viewAll:'View all',uploadLOC:'Upload new letter of claim',newClaim:'New claim',noQueue:'No cases in your queue.',doNow:'Do now',watch:'Watch',portfolio:'Portfolio',waitingOn:'Waiting on',nextAction:'Next action',noTasks:'No immediate tasks for this user.',searchCases:'Search cases…',demoGuideTitle:'Demo path',demoGuideText:'Open urgent case AC-2026-0089 → Request evidence → Switch to Emma Hughes → Complete in Repository',openDemoCase:'Open demo case',stage_intake:'Intake',stage_triage:'Triage',stage_cpr:'CPR',stage_evidence:'Evidence',stage_drafting:'Drafting',stage_defence:'Defence',stage_resolve:'Resolve'},
  fr:{work:'Travail',requests:'Demandes',insights:'Analyses',dashboard:'Tableau de bord',intake:'Réception',cases:'Dossiers',cpr:'Délais',evidence:'Preuves',drafting:'Rédaction',mi:'Reporting',knowledge:'Ressources',repository:'Référentiel',myCases:'Mes dossiers',intakeQueue:'File de réception',cprWatch:'Surveillance délais',myPipeline:'Mon pipeline',legalNews:'Actualités juridiques',networkOps:'Réseau & opérations',liveSources:'Sources en direct',goodMorning:'Bonjour',goodAfternoon:'Bon après-midi',goodEvening:'Bonsoir',noUrgentDeadlines:'Aucun délai urgent cette semaine',evidenceProgress:'Avancement des preuves',cprDeadlines:'Délais de procédure',viewAll:'Voir tout',uploadLOC:'Déposer une lettre de réclamation',newClaim:'Nouvelle réclamation',noQueue:'Aucun dossier dans votre file.',doNow:'À faire',watch:'Surveillance',portfolio:'Portefeuille',waitingOn:'En attente de',nextAction:'Prochaine action',noTasks:'Aucune tâche immédiate.',searchCases:'Rechercher…',demoGuideTitle:'Parcours démo',demoGuideText:'Ouvrir AC-2026-0089 → Demander des preuves → Emma Hughes → Compléter dans le référentiel',openDemoCase:'Ouvrir la démo',stage_intake:'Réception',stage_triage:'Triage',stage_cpr:'Délais',stage_evidence:'Preuves',stage_drafting:'Rédaction',stage_defence:'Défense',stage_resolve:'Résolu'},
  es:{work:'Trabajo',requests:'Solicitudes',insights:'Análisis',dashboard:'Panel',intake:'Recepción',cases:'Casos',cpr:'Plazos',evidence:'Pruebas',drafting:'Redacción',mi:'Informes',knowledge:'Recursos',repository:'Repositorio',myCases:'Mis casos',intakeQueue:'Cola de recepción',cprWatch:'Vigilancia de plazos',myPipeline:'Mi flujo de trabajo',legalNews:'Noticias jurídicas',networkOps:'Red & operaciones',liveSources:'Fuentes en vivo',goodMorning:'Buenos días',goodAfternoon:'Buenas tardes',goodEvening:'Buenas noches',noUrgentDeadlines:'Sin plazos urgentes esta semana',evidenceProgress:'Progreso de pruebas',cprDeadlines:'Plazos procesales',viewAll:'Ver todo',uploadLOC:'Cargar carta de reclamación',newClaim:'Nueva reclamación',noQueue:'No hay casos en su cola.',doNow:'Hacer ahora',watch:'Vigilar',portfolio:'Cartera',waitingOn:'Esperando',nextAction:'Siguiente acción',noTasks:'Sin tareas inmediatas.',searchCases:'Buscar casos…',demoGuideTitle:'Ruta demo',demoGuideText:'Abrir AC-2026-0089 → Solicitar pruebas → Emma Hughes → Completar en repositorio',openDemoCase:'Abrir demo',stage_intake:'Recepción',stage_triage:'Triaje',stage_cpr:'Plazos',stage_evidence:'Pruebas',stage_drafting:'Redacción',stage_defence:'Defensa',stage_resolve:'Resuelto'},
};
const ALL_CASES=[
  {ref:'AC-2026-0089',assignedTo:'SB',claimant:'Daniel Hartley',solicitor:'Pemberton & Associates',flight:'HC 1184 — LTN → BCN',flightNum:'HC 1184',dep:'LTN',arr:'BCN',flightDate:'14 March 2026',value:'£39,000+',type:'EC261 — Diversion',locDate:'22 May 2026',stage:'evidence',cat:'C',jurisdiction:'england-wales',lang:'en',disruptionType:'Weather',classification:'ESCALATE',evidencePct:35,cprDaysLeft:3,points:[{n:1,claim:'Delay — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'TOPS confirmed'},{n:2,claim:'Extraordinary circumstances — weather',evidenceStatus:'amber',evidenceDoc:'METAR/SIGMET pending'},{n:3,claim:'Article 9 — duty of care',evidenceStatus:'red',evidenceDoc:'Valencia ground records outstanding'},{n:4,claim:'Consequential loss — £38,250',evidenceStatus:'red',evidenceDoc:'No counter-evidence'},{n:5,claim:'Travel & subsistence — £141.80',evidenceStatus:'amber',evidenceDoc:'Receipts pending'}],loaStatus:'approved',triageNote:'Complex. Escalate on consequential loss.',activity:[{text:'Evidence module opened',time:'Today 09:14',type:'create'},{text:'AI triage — ESCALATE flagged',time:'Yesterday 16:30',type:'ai'}]},
  {ref:'AC-2026-0101',assignedTo:'SB',claimant:'Angela Foster',solicitor:'Clarke & Partners',flight:'HC 203 — LGW → ALC',flightNum:'HC 203',dep:'LGW',arr:'ALC',flightDate:'20 May 2026',value:'€250',type:'EC261 — Weather delay',locDate:'30 May 2026',stage:'intake',cat:'A',jurisdiction:'england-wales',lang:'en',disruptionType:'Weather',classification:'DEFEND',evidencePct:0,cprDaysLeft:21,points:[],loaStatus:'',triageNote:'',activity:[{text:'LOC received',time:'Today 07:55',type:'create'}]},
  {ref:'AC-2026-0091',assignedTo:'JP',claimant:'Rebecca Walsh',solicitor:'Clarke & Partners',flight:'HC 307 — MAN → AMS',flightNum:'HC 307',dep:'MAN',arr:'AMS',flightDate:'9 April 2026',value:'€250',type:'EC261 — ATC delay',locDate:'4 June 2026',stage:'triage',cat:'A',jurisdiction:'england-wales',lang:'en',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:0,cprDaysLeft:21,points:[{n:1,claim:'Delay 3hrs 36mins — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'Confirmed via TOPS'},{n:2,claim:'Extraordinary circumstances — ATC ATFM',evidenceStatus:'amber',evidenceDoc:'Eurocontrol data requested'},{n:3,claim:'Art 9 — refreshments not provided',evidenceStatus:'red',evidenceDoc:'Ground records required'},{n:4,claim:'Expenses — £18.40',evidenceStatus:'amber',evidenceDoc:'Receipts with LOC'}],loaStatus:'',triageNote:'',activity:[{text:'LOC uploaded — triage pending',time:'Today 10:30',type:'create'}]},
  {ref:'AC-2026-0076',assignedTo:'JP',claimant:'Sarah Taylor',solicitor:'Thompsons Solicitors',flight:'HC 330 — LGW → ALC',flightNum:'HC 330',dep:'LGW',arr:'ALC',flightDate:'28 April 2026',value:'€400',type:'EC261 — Weather delay',locDate:'22 May 2026',stage:'drafting',cat:'B',jurisdiction:'england-wales',lang:'en',disruptionType:'Weather',classification:'DEFEND',evidencePct:100,cprDaysLeft:7,points:[{n:1,claim:'Delay 4hrs 10mins — Art 7(1)(b)',evidenceStatus:'green',evidenceDoc:'TOPS confirmed'},{n:2,claim:'Extraordinary circumstances — weather',evidenceStatus:'green',evidenceDoc:'METAR/SIGMET confirmed'}],loaStatus:'sent',triageNote:'Clean weather case. Evidence complete. Draft LOR.',activity:[{text:'Evidence complete — LOR ready',time:'28 May 16:00',type:'stage'}]},
  {ref:'AC-2026-0094',assignedTo:'KR',claimant:'Thomas Morrison',solicitor:'Irwin Mitchell LLP',flight:'HC 442 — LGW → BCN',flightNum:'HC 442',dep:'LGW',arr:'BCN',flightDate:'15 May 2026',value:'€250',type:'EC261 — ATC delay',locDate:'28 May 2026',stage:'intake',cat:'A',jurisdiction:'england-wales',lang:'en',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:0,cprDaysLeft:15,points:[],loaStatus:'',triageNote:'',activity:[{text:'LOC received',time:'28 May 08:00',type:'create'}]},
  {ref:'AC-2026-0079',assignedTo:'KR',claimant:'James Singh',solicitor:'Slater & Gordon',flight:'HC 556 — LHR → DUB',flightNum:'HC 556',dep:'LHR',arr:'DUB',flightDate:'10 May 2026',value:'€250',type:'EC261 — ATC delay',locDate:'20 May 2026',stage:'evidence',cat:'A',jurisdiction:'england-wales',lang:'en',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:45,cprDaysLeft:18,points:[{n:1,claim:'Delay 3hrs 15mins — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'TOPS confirmed'},{n:2,claim:'Extraordinary circumstances — ATC',evidenceStatus:'amber',evidenceDoc:'Eurocontrol pending'}],loaStatus:'sent',triageNote:'Straightforward ATC.',activity:[{text:'Evidence pack opened',time:'22 May 11:00',type:'action'}]},
  {ref:'FR-2026-0012',assignedTo:'MD',claimant:'Jean-Pierre Moreau',solicitor:'Cabinet Lefèvre',flight:'HC 742 — CDG → LTN',flightNum:'HC 742',dep:'CDG',arr:'LTN',flightDate:'3 March 2026',value:'250 €',type:'CE 261/2004 — Retard',locDate:'12 Mai 2026',stage:'triage',cat:'A',jurisdiction:'france',lang:'fr',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:0,cprDaysLeft:48,points:[{n:1,claim:'Retard de 3h42 — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'Données TOPS confirmées'},{n:2,claim:'Circonstances extraordinaires — ATC',evidenceStatus:'amber',evidenceDoc:'Données Eurocontrol demandées'},{n:3,claim:'Art 9 — absence de rafraîchissements',evidenceStatus:'red',evidenceDoc:'Registres requis'}],loaStatus:'',triageNote:'',activity:[{text:'Lettre de réclamation reçue',time:'12 mai 09:00',type:'create'}]},
  {ref:'FR-2026-0018',assignedTo:'MD',claimant:'Sophie Blanchard',solicitor:'Maître Rousseau',flight:'HC 519 — LYS → LGW',flightNum:'HC 519',dep:'LYS',arr:'LGW',flightDate:'14 Avril 2026',value:'400 €',type:'CE 261/2004 — Annulation',locDate:'28 Mai 2026',stage:'evidence',cat:'B',jurisdiction:'france',lang:'fr',disruptionType:'Weather',classification:'DEFEND',evidencePct:40,cprDaysLeft:32,points:[{n:1,claim:'Annulation le jour même — Art 5(1)(c)',evidenceStatus:'green',evidenceDoc:'Données TOPS confirmées'},{n:2,claim:'Circonstances extraordinaires — météo',evidenceStatus:'amber',evidenceDoc:'METAR LYS obtenu, SIGMET en attente'},{n:3,claim:'Art 8 — absence de réacheminement',evidenceStatus:'red',evidenceDoc:'Dossier requis'}],loaStatus:'sent',triageNote:'Défense météo. Obtenir SIGMET Lyon.',activity:[{text:'METAR LYS obtenu',time:'2 juin 09:30',type:'upload'}]},
  {ref:'FR-2026-0009',assignedTo:'PL',claimant:'Isabelle Fontaine',solicitor:'Maître Dumas',flight:'HC 881 — MRS → LGW',flightNum:'HC 881',dep:'MRS',arr:'LGW',flightDate:'18 Fév 2026',value:'250 €',type:'CE 261/2004 — Retard',locDate:'15 Avril 2026',stage:'drafting',cat:'A',jurisdiction:'france',lang:'fr',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:100,cprDaysLeft:14,points:[{n:1,claim:'Retard de 3h28 — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'Confirmé'},{n:2,claim:'Circonstances extraordinaires — ATFM',evidenceStatus:'green',evidenceDoc:'Données Eurocontrol confirmées'}],loaStatus:'sent',triageNote:'Dossier propre. Rédiger lettre de réponse.',activity:[{text:'Dossier complet',time:'28 mai 15:00',type:'stage'}]},
  {ref:'FR-2026-0021',assignedTo:'PL',claimant:'Antoine Renard',solicitor:'Cabinet Girard',flight:'HC 334 — NCE → LTN',flightNum:'HC 334',dep:'NCE',arr:'LTN',flightDate:'22 Avril 2026',value:'250 €',type:'CE 261/2004 — Retard',locDate:'2 Juin 2026',stage:'intake',cat:'A',jurisdiction:'france',lang:'fr',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:0,cprDaysLeft:58,points:[],loaStatus:'',triageNote:'',activity:[{text:'Lettre de réclamation reçue',time:'2 juin 14:00',type:'create'}]},
  {ref:'ES-2026-0031',assignedTo:'CG',claimant:'Miguel Torres',solicitor:'Bufete Sánchez',flight:'HC 612 — BCN → LGW',flightNum:'HC 612',dep:'BCN',arr:'LGW',flightDate:'5 Marzo 2026',value:'250 €',type:'CE 261/2004 — Retraso',locDate:'20 Mayo 2026',stage:'evidence',cat:'A',jurisdiction:'spain',lang:'es',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:60,cprDaysLeft:10,points:[{n:1,claim:'Retraso de 3h52 — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'Datos TOPS confirmados'},{n:2,claim:'Circunstancias extraordinarias — ATC',evidenceStatus:'amber',evidenceDoc:'Datos Eurocontrol solicitados'},{n:3,claim:'Art 9 — ausencia de atención',evidenceStatus:'red',evidenceDoc:'Registros pendientes'}],loaStatus:'sent',triageNote:'Caso ATC. Obtener Eurocontrol.',activity:[{text:'METAR BCN obtenido',time:'27 mayo 09:00',type:'upload'}]},
  {ref:'ES-2026-0038',assignedTo:'CG',claimant:'Laura Gómez',solicitor:'Despacho Fernández',flight:'HC 228 — MAD → LTN',flightNum:'HC 228',dep:'MAD',arr:'LTN',flightDate:'17 Abril 2026',value:'400 €',type:'CE 261/2004 — Retraso',locDate:'28 Mayo 2026',stage:'triage',cat:'B',jurisdiction:'spain',lang:'es',disruptionType:'Weather',classification:'DEFEND',evidencePct:0,cprDaysLeft:22,points:[{n:1,claim:'Retraso de 4h15 — Art 7(1)(b)',evidenceStatus:'green',evidenceDoc:'Confirmado por TOPS'},{n:2,claim:'Circunstancias extraordinarias — meteorología',evidenceStatus:'amber',evidenceDoc:'METAR/SIGMET pendiente'}],loaStatus:'',triageNote:'',activity:[{text:'Carta de reclamación recibida',time:'28 mayo 11:00',type:'create'}]},
  {ref:'ES-2026-0044',assignedTo:'IM',claimant:'Roberto Jiménez',solicitor:'Abogados Castellano',flight:'HC 471 — VLC → LGW',flightNum:'HC 471',dep:'VLC',arr:'LGW',flightDate:'2 Mayo 2026',value:'250 €',type:'CE 261/2004 — Retraso',locDate:'1 Junio 2026',stage:'intake',cat:'A',jurisdiction:'spain',lang:'es',disruptionType:'ATC Restrictions',classification:'DEFEND',evidencePct:0,cprDaysLeft:29,points:[],loaStatus:'',triageNote:'',activity:[{text:'Carta de reclamación recibida',time:'1 junio 09:30',type:'create'}]},
  {ref:'ES-2026-0027',assignedTo:'IM',claimant:'Carmen Ruiz',solicitor:'Bufete Morales',flight:'HC 339 — AGP → LTN',flightNum:'HC 339',dep:'AGP',arr:'LTN',flightDate:'8 Marzo 2026',value:'250 €',type:'CE 261/2004 — Retraso',locDate:'10 Abril 2026',stage:'drafting',cat:'A',jurisdiction:'spain',lang:'es',disruptionType:'Weather',classification:'DEFEND',evidencePct:100,cprDaysLeft:9,points:[{n:1,claim:'Retraso de 3h18 — Art 7(1)(a)',evidenceStatus:'green',evidenceDoc:'Confirmado'},{n:2,claim:'Circunstancias extraordinarias — meteorología',evidenceStatus:'green',evidenceDoc:'METAR/SIGMET confirmados'}],loaStatus:'sent',triageNote:'Caso limpio. Redactar escrito.',activity:[{text:'Expediente completo',time:'20 mayo 14:00',type:'stage'}]},
];
// Helpers
function getCasesForUser(uid,stage){return ALL_CASES.filter(function(c){return c.assignedTo===uid&&(!stage||c.stage===stage);});}
function getCase(ref){return ALL_CASES.find(function(c){return c.ref===ref;})||null;}
function getJurisdiction(key){return JURISDICTIONS[key]||JURISDICTIONS['england-wales'];}
function daysUrgency(d){return d<=3?'urgent':d<=7?'warn':'ok';}
function urgencyLabel(d){return d<=3?d+'d — URGENT':d<=7?d+'d':d+'d';}
function stageIcon(s){var m={intake:'ti-inbox',triage:'ti-search',cpr:'ti-calendar-due',evidence:'ti-folder-open',drafting:'ti-file-pencil',defence:'ti-shield',resolve:'ti-circle-check'};return m[s]||'ti-file';}
function stageColor(s){var m={intake:'#1D4ED8',triage:'#92400E',cpr:'#B45309',evidence:'#4338CA',drafting:'#065F46',defence:'#1A7A4A',resolve:'#374151'};return m[s]||'#374151';}
function stageBg(s){var m={intake:'#EFF6FF',triage:'#FEF3C7',cpr:'#FEF9C3',evidence:'#EEEDFE',drafting:'#E6F5EE',defence:'#DCFCE7',resolve:'#F1F5F9'};return m[s]||'#F1F5F9';}
function evPctColor(p){return p>=70?'#22A863':p>=40?'#F59E0B':'#C0392B';}
function getActiveUser(){return sessionStorage.getItem('261c_user')||'SB';}
function setActiveUser(id){sessionStorage.setItem('261c_user',id);}
function getUILang(){return sessionStorage.getItem('261c_lang')||(USERS[getActiveUser()]&&USERS[getActiveUser()].lang)||'en';}
function t(key){var d=I18N[getUILang()]||I18N.en;return d[key]||I18N.en[key]||key;}
